from node:20-alpine

WORKDIR /app

# 1. 先安裝系統工具
RUN apk add --no-cache curl

# 2. 複製 package.json 並安裝依賴（利用 Docker 快取機制）
COPY package*.json ./
RUN npm install && npm install axios 


# 複製其餘原始碼
COPY . .

# 預設 React 埠號
EXPOSE 3000

# 啟動開發伺服器

CMD ["npm", "start"]


# dockerfile 啟動指令
# docker build -f ./dockerfile.hov -t hov_fe_img:1.0 .


# 容器創建指令
# docker run -d -p 3000:3000 --name hov_fe -v ${pwd}:/app    hov_fe_img:1.0
#  docker run -d -p 3000:3000 --name hov_fe -v ${PWD}:/app -v /app/node_modules -e CHOKIDAR_USEPOLLING=true hov_fe_img:1.0
